<?php
declare(strict_types=1);
require __DIR__ . '/../lib/game.php';
function ok(bool $condition, string $message): void { if (!$condition) { fwrite(STDERR, "FAIL: $message\n"); exit(1); } echo "ok - $message\n"; }
$seed=load_seed();ok(count($seed['players'])>=3,'players loaded');ok(count($seed['questions'])>=100,'question bank loaded');ok(count(discover_csv_files('questions'))>=1,'question CSV shards discovered dynamically');
$runtime=empty_state();$bankId=$seed['banks'][0]['bankId'];$categoryId=array_values(array_filter($seed['categories'],fn($c)=>$c['bankId']===$bankId&&$c['active']))[0]['categoryId'];
$d=create_match($runtime,['name'=>'Smoke','bankId'=>$bankId,'playerIds'=>['J1','J3'],'startingPlayerId'=>'J3','categoryIds'=>[$categoryId],'levelKeys'=>array_column($seed['levels'],'levelKey')]);ok($d['state']['currentPlayerId']==='J3','starting player is respected');
$first=select_question($seed,$runtime,$d['match'],$categoryId);$again=select_question($seed,$runtime,$d['match'],$categoryId);ok($first!==null&&$again!==null,'selector returns a question');ok($first['question']['questionKey']===$again['question']['questionKey']&&$first['levelKey']===$again['levelKey'],'selector is deterministic');
$d=perform_action($runtime,$d['match']['matchId'],['action'=>'draw','categoryId'=>$categoryId]);$key=$d['state']['currentDraw']['questionKey'];ok(isset(global_used_keys($seed,$runtime)[$key]),'shown question is globally excluded');$d=perform_action($runtime,$d['match']['matchId'],['action'=>'reveal']);$d=perform_action($runtime,$d['match']['matchId'],['action'=>'result','correct'=>false]);ok($d['state']['currentPlayerId']==='J1','wrong answer rotates the turn');ok(count(compute_stats($seed,$runtime)['rows'])>0,'statistics merge historical and server results');echo "All PHP smoke tests passed.\n";
