import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseCsv, rowsToObjects } from '../src/csv.js';
const root=new URL('../data/',import.meta.url);const qFiles=['AL','LI','FI','HI','IN','NE'].map(id=>`questions-${id}.csv`);const aFiles=['J1','J2','J3'].map(id=>`attempts-${id}.csv`);const files=['meta.csv','banks.csv','categories.csv','levels.csv',...qFiles,'players.csv','matches.csv','participants.csv',...aFiles,'exposures.csv','events.csv'];
const readRows=name=>rowsToObjects(parseCsv(fs.readFileSync(fileURLToPath(new URL(name,root)),'utf8')));
test('todos los CSV son UTF-8 sin BOM y usan CRLF',()=>{for(const name of files){const p=fileURLToPath(new URL(name,root));const bytes=fs.readFileSync(p);assert.notDeepEqual([...bytes.subarray(0,3)],[0xef,0xbb,0xbf],`${name} no debe tener BOM`);assert.ok(bytes.includes(Buffer.from('\r\n')),`${name} debe usar CRLF`);new TextDecoder('utf-8',{fatal:true}).decode(bytes)}});
test('el banco canónico limpio contiene 126 preguntas y claves únicas',()=>{const rows=qFiles.flatMap(readRows);assert.equal(rows.length,126);assert.equal(new Set(rows.map(r=>r.question_key)).size,126);assert.equal(rows.some(r=>r.status==='discarded'),false);for(const id of ['FI-012','HI-007','IN-007','IN-018'])assert.equal(rows.some(r=>r.question_id===id),false)});
test('la semilla no conserva exposiciones históricas de limpieza',()=>{assert.equal(readRows('exposures.csv').length,0)});
test('Nebrija está normalizado como acierto ordinario sin rastro de rectificación',()=>{const rows=aFiles.flatMap(readRows);const a=rows.find(r=>r.question_no==='23');assert.equal(a.player_id,'J2');assert.equal(a.question_id,'LI-014');assert.equal(a.correct,'true');assert.equal(a.quesito_attempt,'false');assert.equal(a.quesito_won,'false');assert.equal(a.notes,'ninguna; J2 acertó.');assert.doesNotMatch(a.notes,/corre|rectific|no era|morado/i)});
