import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseCsv, rowsToObjects } from '../src/csv.js';
const root=new URL('../data/',import.meta.url);const qFiles=['AL','LI','FI','HI','IN','NE'].map(id=>`questions-${id}.csv`);const aFiles=['J1','J2','J3'].map(id=>`attempts-${id}.csv`);const files=['meta.csv','banks.csv','categories.csv','levels.csv',...qFiles,'players.csv','matches.csv','participants.csv',...aFiles,'exposures.csv','events.csv'];
const readRows=name=>rowsToObjects(parseCsv(fs.readFileSync(fileURLToPath(new URL(name,root)),'utf8')));
test('todos los CSV son UTF-8 sin BOM y usan CRLF',()=>{for(const name of files){const p=fileURLToPath(new URL(name,root));const bytes=fs.readFileSync(p);assert.notDeepEqual([...bytes.subarray(0,3)],[0xef,0xbb,0xbf],`${name} no debe tener BOM`);assert.ok(bytes.includes(Buffer.from('\r\n')),`${name} debe usar CRLF`);new TextDecoder('utf-8',{fatal:true}).decode(bytes)}});
test('el banco canónico limpio contiene 126 preguntas y claves únicas',()=>{const rows=qFiles.flatMap(readRows);assert.equal(rows.length,126);assert.equal(new Set(rows.map(r=>r.question_key)).size,126);assert.equal(rows.some(r=>r.status==='discarded'),false)});
test('la semilla histórica no conserva exposiciones descartadas',()=>{assert.equal(readRows('exposures.csv').length,0)});
test('el histórico contiene solo el estado final aceptado',()=>{const rows=aFiles.flatMap(readRows);assert.equal(rows.some(r=>/correcci[oó]n|rectific|no era pregunta/i.test(r.notes??'')),false);const j2Quesitos=rows.filter(r=>r.player_id==='J2'&&r.quesito_won==='true').length;assert.equal(j2Quesitos,1)});
