from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
VAR_DIR = ROOT / "var"
SCHEMA_VERSION = 8
EVENT_SCHEMA_VERSION = 3
RULES_VERSION = "trivial-rules-4.0.0"
BUILD_VERSION = "2026-08-20.1"
LOW_STOCK_THRESHOLD = 5

EVENT_TYPES = {
    "MATCH_CREATED",
    "TURN_SELECTED",
    "QUESTION_DRAWN",
    "ANSWER_REVEALED",
    "RESULT_RECORDED",
    "QUESTION_DISCARDED",
    "MATCH_CLOSED",
    "EVENT_REVERTED",
    "EVENT_RESTORED",
}
