import { db } from './db.js';
import { EVENT_TYPES, deriveLiveState, getActiveEvents, getRevertedEventIds, selectQuestionForDraw, freezeLevelWeights, makeMatchSeed, nextPlayerId, quesitosByPlayer, computeStats } from './domain.js';
import { makeEvent, downloadJson } from './import-export.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const E={tabs:$$('.tab'),views:$$('.view'),game:$('#game-root'),stats:$('#stats-root'),base:$('#base-root'),picker:$('#match-picker'),newBtn:$('#new-match-btn'),dlg:$('#new-match-dialog'),form:$('#new-match-form'),players:$('#new-match-players'),cats:$('#new-match-categories'),levels:$('#new-match-levels'),close:$('#close-match-dialog'),cancel:$('#cancel-match'),exp:$('#export-backup'),imp:$('#import-backup'),reset:$('#reset-base'),toast:$('#toast')};
let M={banks:[],questions:[],players:[],matches:[],events:[],attempts:[]}, current=null, category=null, timer;
const node=(tag,a={},kids=[])=>{const n=document.createElement(tag);for(const[k,v]of Object.entries(a)){if(k==='class')n.className=v;else if(k==='text')n.textContent=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2).toLowerCase(),v);else if(k==='disabled')n.disabled=!!v;else if(k==='checked')n.checked=!!v;else if(v===true)n.setAttribute(k,'');else if(v!==false&&v!=null)n.setAttribute(k,String(v));}for(const x of(Array.isArray(kids)?kids:[kids]))if(x!=null)n.append(x instanceof Node?x:document.createTextNode(String(x)));return n};
const toast=t=>{clearTimeout(timer);E.toast.textContent=t;E.toast.classList.add('show');timer=setTimeout(()=>E.toast.classList.remove('show'),3000)};
const pname=id=>M.players.find(p=>p.playerId===id)?.name??id;
const bank=id=>M.banks.find(b=>b.bankId===id);
const match=id=>M.matches.find(m=>m.matchId===id);
const events=id=>M.events.filter(e=>e.matchId===id);
const attempts=id=>M.attempts.filter(a=>a.matchId===id&&a.active!==false);
const qkey=k=>M.questions.find(q=>q.questionKey===k);
const eventId=(mid,seq)=>`${mid}|E${String(seq).padStart(5,'0')}`;
const attemptId=(mid,seq)=>`${mid}|A${String(seq).padStart(5,'0')}`;
const exposureId=(mid,seq)=>`${mid}|X${String(seq).padStart(5,'0')}`;

async function load(){[M.banks,M.questions,M.players,M.matches,M.events,M.attempts]=await Promise.all(['banks','questions','players','matches','events','attempts'].map(x=>db.getAll(x)));M.matches.sort((a,b)=>String(b.createdAt??'').localeCompare(String(a.createdAt??''))||b.matchId.localeCompare(a.matchId));M.events.sort((a,b)=>String(a.matchId).localeCompare(String(b.matchId))||(a.seq??0)-(b.seq??0));if(!current||!match(current))current=M.matches.find(m=>m.status==='open')?.matchId??M.matches[0]?.matchId??null;}
async function refresh(){await load();renderPicker();renderGame();renderStats();renderBase();}
function view(v){E.tabs.forEach(b=>b.classList.toggle('active',b.dataset.view===v));E.views.forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));}
function renderPicker(){E.picker.replaceChildren();if(!M.matches.length){E.picker.append(node('option',{text:'Sin partidas'}));E.picker.disabled=true;return}E.picker.disabled=false;for(const m of M.matches){const o=node('option',{value:m.matchId,text:`${m.name} · ${m.playerIds.join('+')} · ${m.status==='closed'?'cerrada':'abierta'}`});o.selected=m.matchId===current;E.picker.append(o)}}
async function emit(mid,type,payload={}){const es=await db.eventsForMatch(mid),seq=Math.max(0,...es.map(e=>e.seq??0))+1,e=makeEvent(mid,seq,type,payload);e.eventId=eventId(mid,seq);await db.put('events',e);return e;}
function nextMatchId(){const d=new Date(),day=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`,prefix=`M${day}-`,nums=M.matches.filter(m=>m.matchId.startsWith(prefix)).map(m=>Number(m.matchId.slice(prefix.length))||0);return `${prefix}${String(Math.max(0,...nums)+1).padStart(3,'0')}`;}
function stock(m,cid){return M.questions.filter(q=>q.bankId===m.bankId&&q.categoryId===cid&&m.enabledLevelKeys.includes(q.levelKey)&&q.status==='active').length;}

function renderGame(){E.game.replaceChildren();const m=match(current);if(!m){E.game.append(node('div',{class:'empty',text:'Crea una partida para empezar.'}));return}const b=bank(m.bankId),es=events(m.matchId),live=deriveLiveState(m,es),ats=attempts(m.matchId),qs=quesitosByPlayer(ats),cats=(b?.categories??[]).filter(c=>m.enabledCategoryIds.includes(c.categoryId)),pid=live.currentDraw?.playerId??nextPlayerId(m,ats);const wrap=node('div',{class:'grid two'}),main=node('div',{class:'card'}),side=node('div',{class:'card'});main.append(node('p',{class:'eyebrow',text:live.status==='closed'?'PARTIDA CERRADA':'TURNO'}),node('h3',{text:live.status==='closed'?'Partida finalizada':`Juega ${pname(pid)}`}),node('p',{class:'muted',text:`Jugadores: ${m.playerIds.map(pname).join(' → ')} · Categorías: ${m.enabledCategoryIds.length} · Niveles: ${m.enabledLevelKeys.length}`}));if(live.status!=='closed'){if(live.currentDraw)renderQuestion(main,m,b,live,ats);else renderDraw(main,m,b,pid,ats,cats)}side.append(node('p',{class:'eyebrow',text:'QUESITOS'}));for(const p of m.playerIds){const badges=node('div',{class:'badges'});for(const c of cats)badges.append(node('span',{class:'badge',text:`${qs.get(p)?.has(c.categoryId)?'●':'○'} ${c.emoji??''} ${c.label}`}));side.append(node('p',{},[node('strong',{text:pname(p)}),badges]))}side.append(node('hr'));const ctl=node('div',{class:'toolbar'});const canUndo=getActiveEvents(es).some(e=>[EVENT_TYPES.RESULT_RECORDED,EVENT_TYPES.QUESTION_DISCARDED,EVENT_TYPES.MATCH_CLOSED].includes(e.type));ctl.append(node('button',{text:'Deshacer',disabled:!canUndo,onclick:()=>undo(m)}),node('button',{text:'Rehacer',disabled:getRevertedEventIds(es).size===0,onclick:()=>redo(m)}));if(live.status!=='closed')ctl.append(node('button',{class:'danger',text:'Cerrar partida',disabled:!!live.currentDraw,onclick:()=>closeMatch(m)}));side.append(ctl);side.append(node('hr'),node('p',{class:'muted',text:`Semilla: ${m.seed??'histórica'} · pesos de nivel congelados al crear la partida.`}));wrap.append(main,side);E.game.append(wrap)}

function renderDraw(root,m,b,pid,ats,cats){if(!category||!m.enabledCategoryIds.includes(category)||stock(m,category)===0)category=cats.find(c=>stock(m,c.categoryId)>0)?.categoryId??null;const cg=node('div',{class:'category-grid'});for(const c of cats){const n=stock(m,c.categoryId);cg.append(node('button',{class:`category-button${category===c.categoryId?' active':''}`,text:`${c.emoji??''} ${c.label} · ${n}`,disabled:n===0,onclick:()=>{category=c.categoryId;renderGame()}}))}root.append(node('p',{text:'Escoge la categoría indicada por el tablero.'}),cg);if(!category){root.append(node('p',{class:'warning',text:'No quedan preguntas disponibles con la configuración de esta partida.'}));return}const has=quesitosByPlayer(ats).get(pid)?.has(category),lab=node('label',{class:'badge'}),chk=node('input',{type:'checkbox',id:'quesito-toggle',disabled:!!has});chk.style.width='auto';lab.append(chk,document.createTextNode(has?' Quesito ya obtenido':' Esta casilla es de quesito'));root.append(lab);root.append(node('div',{class:'toolbar'},node('button',{class:'primary',text:'Sacar pregunta',onclick:async()=>{await load();const mm=match(m.matchId),aa=attempts(m.matchId),player=nextPlayerId(mm,aa),pool=M.questions.filter(q=>q.bankId===mm.bankId),drawOrdinal=aa.length+1,pick=selectQuestionForDraw({questions:pool,categoryId:category,playerId:player,enabledLevelKeys:mm.enabledLevelKeys,frozenWeights:mm.levelWeights,matchSeed:mm.seed,drawOrdinal});if(!pick){toast('No quedan preguntas elegibles en esa categoría.');await refresh();return}const ev=await emit(mm.matchId,EVENT_TYPES.QUESTION_DRAWN,{questionKey:pick.question.questionKey,playerId:player,categoryId:category,levelKey:pick.levelKey,quesitoAttempt:chk.checked,drawOrdinal,randomUnit:pick.unit,levelWeights:pick.weights});await db.put('questions',{...pick.question,status:'retired',retiredByEventId:ev.eventId,retiredByMatchId:mm.matchId});await refresh()}})))}

function renderQuestion(root,m,b,live,ats){const d=live.currentDraw,q=qkey(d.questionKey);if(!q){root.append(node('p',{class:'warning',text:'Pregunta no encontrada.'}));return}const c=b.categories.find(x=>x.categoryId===d.categoryId),l=b.levels.find(x=>x.levelKey===d.levelKey);root.append(node('div',{class:'badges'},[node('span',{class:'badge',text:`${c?.emoji??''} ${c?.label??d.categoryId}`}),node('span',{class:'badge',text:`Nivel: ${l?.label??d.levelKey}`}),d.quesitoAttempt?node('span',{class:'badge',text:'Quesito'}):null]));root.append(node('div',{class:'question-card'},[node('div',{class:'question-text',text:q.prompt}),node('div',{class:`answer-box${live.answerRevealed?'':' hidden'}`},[node('strong',{text:'Respuesta: '}),q.answer,q.explanation?node('p',{class:'muted',text:q.explanation}):null])]));const bar=node('div',{class:'toolbar'});if(!live.answerRevealed)bar.append(node('button',{text:'Mostrar respuesta',onclick:async()=>{await emit(m.matchId,EVENT_TYPES.ANSWER_REVEALED,{drawEventId:d.eventId,questionKey:d.questionKey});await refresh()}}));bar.append(node('button',{class:'good',text:'Acierto',onclick:()=>result(m,d,ats,true)}),node('button',{class:'danger',text:'Fallo',onclick:()=>result(m,d,ats,false)}),node('button',{text:'Descartar pregunta',onclick:()=>discard(m,d,q)}));root.append(bar)}

async function result(m,d,ats,correct){const won=!!(correct&&d.quesitoAttempt&&!quesitosByPlayer(ats).get(d.playerId)?.has(d.categoryId)),ev=await emit(m.matchId,EVENT_TYPES.RESULT_RECORDED,{drawEventId:d.eventId,questionKey:d.questionKey,playerId:d.playerId,categoryId:d.categoryId,levelKey:d.levelKey,correct,quesitoAttempt:d.quesitoAttempt,quesitoWon:won}),q=qkey(d.questionKey),a={attemptId:attemptId(m.matchId,ev.seq),matchId:m.matchId,questionNo:ats.length+1,playerId:d.playerId,questionKey:d.questionKey,questionId:q?.questionId??d.questionKey.split('|').at(-1),bankId:m.bankId,categoryId:d.categoryId,levelKey:d.levelKey,resultId:correct?'ACI':'FAL',correct,computable:true,quesitoAttempt:d.quesitoAttempt,quesitoWon:won,sourceEventId:ev.eventId,active:true,source:'web',createdAt:new Date().toISOString()};await db.atomicPut({attempts:[a],questions:[{...q,status:'retired'}]});await refresh()}
async function discard(m,d,q){const ev=await emit(m.matchId,EVENT_TYPES.QUESTION_DISCARDED,{drawEventId:d.eventId,questionKey:d.questionKey,playerId:d.playerId,categoryId:d.categoryId,levelKey:d.levelKey,reason:'Descartada durante la partida'});await db.atomicPut({questions:[{...q,status:'discarded'}],exposures:[{exposureId:exposureId(m.matchId,ev.seq),matchId:m.matchId,bankId:m.bankId,questionKey:q.questionKey,questionId:q.questionId,playerId:d.playerId,type:'descartada_expuesta',countsAsAttempt:false,reason:'Descartada durante la partida',source:'web',sourceEventId:ev.eventId,active:true}]});await refresh()}
const reversible=e=>[EVENT_TYPES.RESULT_RECORDED,EVENT_TYPES.QUESTION_DISCARDED,EVENT_TYPES.MATCH_CLOSED].includes(e.type);
async function undo(m){const t=getActiveEvents(events(m.matchId)).filter(reversible).at(-1);if(!t)return;const control=await emit(m.matchId,EVENT_TYPES.EVENT_REVERTED,{targetEventId:t.eventId});if(t.type===EVENT_TYPES.RESULT_RECORDED){const as=await db.getByIndex('attempts','sourceEventId',t.eventId);for(const a of as)await db.put('attempts',{...a,active:false,revertedByEventId:control.eventId})}if(t.type===EVENT_TYPES.QUESTION_DISCARDED){const xs=await db.getByIndex('exposures','sourceEventId',t.eventId);for(const x of xs)await db.put('exposures',{...x,active:false});const q=qkey(t.payload.questionKey);if(q)await db.put('questions',{...q,status:'retired'})}if(t.type===EVENT_TYPES.MATCH_CLOSED)await db.put('matches',{...m,status:'open',closedAt:null,closeReason:null});await refresh()}
async function redo(m){const es=events(m.matchId),rev=getRevertedEventIds(es),t=es.filter(e=>rev.has(e.eventId)&&reversible(e)).at(-1);if(!t)return;await emit(m.matchId,EVENT_TYPES.EVENT_RESTORED,{targetEventId:t.eventId});if(t.type===EVENT_TYPES.RESULT_RECORDED){const as=await db.getByIndex('attempts','sourceEventId',t.eventId);for(const a of as)await db.put('attempts',{...a,active:true})}if(t.type===EVENT_TYPES.QUESTION_DISCARDED){const xs=await db.getByIndex('exposures','sourceEventId',t.eventId);for(const x of xs)await db.put('exposures',{...x,active:true});const q=qkey(t.payload.questionKey);if(q)await db.put('questions',{...q,status:'discarded'})}if(t.type===EVENT_TYPES.MATCH_CLOSED)await db.put('matches',{...m,status:'closed'});await refresh()}
async function closeMatch(m){const ev=await emit(m.matchId,EVENT_TYPES.MATCH_CLOSED,{reason:'Cierre manual'});await db.put('matches',{...m,status:'closed',closedAt:ev.ts,closeReason:'Cierre manual'});await refresh()}

function openDialog(){const b=M.banks[0];E.players.replaceChildren();E.cats.replaceChildren();E.levels.replaceChildren();for(const p of M.players.filter(p=>p.active!==false)){const i=node('input',{type:'checkbox',name:'player',value:p.playerId});E.players.append(node('label',{},[i,p.name]))}for(const c of b.categories){const i=node('input',{type:'checkbox',name:'category',value:c.categoryId,checked:true});E.cats.append(node('label',{},[i,`${c.emoji??''} ${c.label}`]))}for(const l of b.levels){const i=node('input',{type:'checkbox',name:'level',value:l.levelKey,checked:true});E.levels.append(node('label',{},[i,l.label]))}E.dlg.showModal()}
async function createMatch(ev){ev.preventDefault();const b=M.banks[0],pids=$$('input[name="player"]:checked').map(i=>i.value),cids=$$('input[name="category"]:checked').map(i=>i.value),lids=$$('input[name="level"]:checked').map(i=>i.value);if(pids.length<1||pids.length>3)return toast('Selecciona entre 1 y 3 jugadores.');if(!cids.length)return toast('Selecciona al menos una categoría.');if(!lids.length)return toast('Selecciona al menos un nivel.');const pool=M.questions.filter(q=>q.bankId===b.bankId),bad=cids.filter(cid=>!pool.some(q=>q.categoryId===cid&&lids.includes(q.levelKey)&&q.status==='active'));if(bad.length)return toast(`Sin stock para los niveles elegidos en: ${bad.map(id=>b.categories.find(c=>c.categoryId===id)?.label??id).join(', ')}.`);const id=nextMatchId(),seed=makeMatchSeed({matchId:id,playerIds:pids,categoryIds:cids,levelKeys:lids,bankId:b.bankId}),weights=freezeLevelWeights({questions:pool,categoryIds:cids,enabledLevelKeys:lids}),fd=new FormData(E.form),m={matchId:id,name:String(fd.get('name')||'').trim()||`Partida ${new Date().toLocaleDateString('es-ES')}`,bankId:b.bankId,playerIds:pids,enabledCategoryIds:cids,enabledLevelKeys:lids,levelWeights:weights,seed,status:'open',createdAt:new Date().toISOString(),configVersion:3,source:'web'},parts=pids.map((p,i)=>({matchPlayerId:`${id}|${p}`,matchId:id,playerId:p,seatNo:i+1,active:true}));await db.atomicPut({matches:[m],participants:parts});await emit(id,EVENT_TYPES.MATCH_CREATED,{playerIds:pids,enabledCategoryIds:cids,enabledLevelKeys:lids,seed,levelWeights:weights});current=id;category=cids[0];E.dlg.close();E.form.reset();await refresh();view('game')}

function renderStats(){E.stats.replaceChildren();const s=computeStats(M.attempts,M.matches);if(!s.byPlayer.length){E.stats.append(node('div',{class:'empty',text:'Sin resultados.'}));return}const g=node('div',{class:'grid three'});for(const r of s.byPlayer.sort((a,b)=>a.playerId.localeCompare(b.playerId)))g.append(node('div',{class:'card'},[node('p',{class:'eyebrow',text:pname(r.playerId)}),node('div',{class:'kpi',text:`${Math.round(r.precision*100)}%`}),node('p',{class:'muted',text:`${r.correct}/${r.resolved} aciertos · ${r.quesitosWon} quesitos`})]));E.stats.append(g);const t=node('table');t.append(node('thead',{},node('tr',{},['Jugador','Categoría','Nivel','Aciertos','Intentos','Precisión'].map(x=>node('th',{text:x})))));const body=node('tbody');for(const p of M.players)for(const c of M.banks[0].categories)for(const l of M.banks[0].levels){const aa=M.attempts.filter(a=>a.active!==false&&a.computable!==false&&a.correct!==null&&a.correct!==undefined&&a.playerId===p.playerId&&a.categoryId===c.categoryId&&a.levelKey===l.levelKey);if(!aa.length)continue;const ok=aa.filter(a=>a.correct).length;body.append(node('tr',{},[p.name,`${c.emoji??''} ${c.label}`,l.label,ok,aa.length,`${Math.round(ok/aa.length*100)}%`].map(x=>node('td',{text:x}))))}t.append(body);E.stats.append(node('div',{class:'card',style:'margin-top:1rem'},t))}
function renderBase(){E.base.replaceChildren();const b=M.banks[0];if(!b)return;const active=M.questions.filter(q=>q.status==='active').length,ret=M.questions.filter(q=>q.status==='retired').length,dis=M.questions.filter(q=>q.status==='discarded').length;E.base.append(node('div',{class:'grid three'},[node('div',{class:'card'},[node('div',{class:'kpi',text:String(M.questions.length)}),node('p',{text:'preguntas integradas'})]),node('div',{class:'card'},[node('div',{class:'kpi',text:String(active)}),node('p',{text:'disponibles'})]),node('div',{class:'card'},[node('div',{class:'kpi',text:String(dis)}),node('p',{text:`descartadas · ${ret} administradas`})])]))}
async function exportAll(){downloadJson(`trivial-backup-${new Date().toISOString().slice(0,10)}.json`,await db.exportAll())}
async function importAll(f){const p=JSON.parse(await f.text());await db.importAll(p,{replace:true});current=null;await refresh();toast('Copia restaurada.')}

E.tabs.forEach(b=>b.onclick=()=>view(b.dataset.view));E.picker.onchange=()=>{current=E.picker.value;category=null;renderGame()};E.newBtn.onclick=openDialog;E.close.onclick=E.cancel.onclick=()=>E.dlg.close();E.form.onsubmit=createMatch;E.exp.onclick=exportAll;E.imp.onchange=async()=>{if(E.imp.files[0])await importAll(E.imp.files[0]);E.imp.value=''};E.reset.onclick=async()=>{if(confirm('¿Restaurar la base integrada y borrar partidas locales posteriores?')){await db.resetToSeed();current=null;category=null;await refresh();toast('Base original restaurada.')}};
window.addEventListener('error',e=>{console.error(e.error??e.message);toast('Error de aplicación. Revisa la consola.')});
await db.init();await refresh();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);
